[package]
name = "tcp_source"
version = "0.1.0"
edition = "2021"

[dependencies]
parquet = { version = "52.0.0", features = ["json"] }
clap = { version = "4.5.7", features = ["derive"] }
log = "0.4.21"
tracing = "0.1.40"
tracing-appender = "0.2.3"
tracing-subscriber = "0.3.18"
tokio = { version = "1.38.0", features = ["full"] }
crossbeam-channel = "0.5.13"
